// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tz/v1/metrics.proto

package tzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricReport is a single snapshot of system metrics from one agent.
type MetricReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host identifier (hostname or custom label from agent config).
	HostId string `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	// Timestamp when the metrics were collected (agent-side time).
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cpu           *CPU                   `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *Memory                `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks         []*Disk                `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks      []*Network             `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricReport) Reset() {
	*x = MetricReport{}
	mi := &file_tz_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricReport) ProtoMessage() {}

func (x *MetricReport) ProtoReflect() protoreflect.Message {
	mi := &file_tz_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricReport.ProtoReflect.Descriptor instead.
func (*MetricReport) Descriptor() ([]byte, []int) {
	return file_tz_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricReport) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *MetricReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricReport) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricReport) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricReport) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricReport) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

type CPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent  float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	UserPercent   float64                `protobuf:"fixed64,2,opt,name=user_percent,json=userPercent,proto3" json:"user_percent,omitempty"`
	SystemPercent float64                `protobuf:"fixed64,3,opt,name=system_percent,json=systemPercent,proto3" json:"system_percent,omitempty"`
	IdlePercent   float64                `protobuf:"fixed64,4,opt,name=idle_percent,json=idlePercent,proto3" json:"idle_percent,omitempty"`
	IowaitPercent float64                `protobuf:"fixed64,5,opt,name=iowait_percent,json=iowaitPercent,proto3" json:"iowait_percent,omitempty"`
	LogicalCount  uint32                 `protobuf:"varint,6,opt,name=logical_count,json=logicalCount,proto3" json:"logical_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_tz_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_tz_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_tz_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *CPU) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CPU) GetUserPercent() float64 {
	if x != nil {
		return x.UserPercent
	}
	return 0
}

func (x *CPU) GetSystemPercent() float64 {
	if x != nil {
		return x.SystemPercent
	}
	return 0
}

func (x *CPU) GetIdlePercent() float64 {
	if x != nil {
		return x.IdlePercent
	}
	return 0
}

func (x *CPU) GetIowaitPercent() float64 {
	if x != nil {
		return x.IowaitPercent
	}
	return 0
}

func (x *CPU) GetLogicalCount() uint32 {
	if x != nil {
		return x.LogicalCount
	}
	return 0
}

type Memory struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes      uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes       uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailableBytes  uint64                 `protobuf:"varint,3,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	UsedPercent     float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	SwapTotalBytes  uint64                 `protobuf:"varint,5,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"`
	SwapUsedBytes   uint64                 `protobuf:"varint,6,opt,name=swap_used_bytes,json=swapUsedBytes,proto3" json:"swap_used_bytes,omitempty"`
	SwapUsedPercent float64                `protobuf:"fixed64,7,opt,name=swap_used_percent,json=swapUsedPercent,proto3" json:"swap_used_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_tz_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_tz_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_tz_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Memory) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Memory) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *Memory) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *Memory) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *Memory) GetSwapTotalBytes() uint64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

func (x *Memory) GetSwapUsedBytes() uint64 {
	if x != nil {
		return x.SwapUsedBytes
	}
	return 0
}

func (x *Memory) GetSwapUsedPercent() float64 {
	if x != nil {
		return x.SwapUsedPercent
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mountpoint    string                 `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Fstype        string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,7,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	ReadBytes     uint64                 `protobuf:"varint,8,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    uint64                 `protobuf:"varint,9,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_tz_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_tz_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_tz_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *Disk) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Disk) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *Disk) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Disk) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *Disk) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *Disk) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *Disk) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *Disk) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,5,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	ErrorsSent    uint64                 `protobuf:"varint,6,opt,name=errors_sent,json=errorsSent,proto3" json:"errors_sent,omitempty"`
	ErrorsRecv    uint64                 `protobuf:"varint,7,opt,name=errors_recv,json=errorsRecv,proto3" json:"errors_recv,omitempty"`
	DropsSent     uint64                 `protobuf:"varint,8,opt,name=drops_sent,json=dropsSent,proto3" json:"drops_sent,omitempty"`
	DropsRecv     uint64                 `protobuf:"varint,9,opt,name=drops_recv,json=dropsRecv,proto3" json:"drops_recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_tz_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_tz_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_tz_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *Network) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Network) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Network) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *Network) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *Network) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *Network) GetErrorsSent() uint64 {
	if x != nil {
		return x.ErrorsSent
	}
	return 0
}

func (x *Network) GetErrorsRecv() uint64 {
	if x != nil {
		return x.ErrorsRecv
	}
	return 0
}

func (x *Network) GetDropsSent() uint64 {
	if x != nil {
		return x.DropsSent
	}
	return 0
}

func (x *Network) GetDropsRecv() uint64 {
	if x != nil {
		return x.DropsRecv
	}
	return 0
}

var File_tz_v1_metrics_proto protoreflect.FileDescriptor

const file_tz_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13tz/v1/metrics.proto\x12\x05tz.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\x01\n" +
	"\fMetricReport\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\x03cpu\x18\x03 \x01(\v2\n" +
	".tz.v1.CPUR\x03cpu\x12%\n" +
	"\x06memory\x18\x04 \x01(\v2\r.tz.v1.MemoryR\x06memory\x12!\n" +
	"\x05disks\x18\x05 \x03(\v2\v.tz.v1.DiskR\x05disks\x12*\n" +
	"\bnetworks\x18\x06 \x03(\v2\x0e.tz.v1.NetworkR\bnetworks\"\xe3\x01\n" +
	"\x03CPU\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12!\n" +
	"\fuser_percent\x18\x02 \x01(\x01R\vuserPercent\x12%\n" +
	"\x0esystem_percent\x18\x03 \x01(\x01R\rsystemPercent\x12!\n" +
	"\fidle_percent\x18\x04 \x01(\x01R\vidlePercent\x12%\n" +
	"\x0eiowait_percent\x18\x05 \x01(\x01R\riowaitPercent\x12#\n" +
	"\rlogical_count\x18\x06 \x01(\rR\flogicalCount\"\x92\x02\n" +
	"\x06Memory\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x03 \x01(\x04R\x0eavailableBytes\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\x12(\n" +
	"\x10swap_total_bytes\x18\x05 \x01(\x04R\x0eswapTotalBytes\x12&\n" +
	"\x0fswap_used_bytes\x18\x06 \x01(\x04R\rswapUsedBytes\x12*\n" +
	"\x11swap_used_percent\x18\a \x01(\x01R\x0fswapUsedPercent\"\x98\x02\n" +
	"\x04Disk\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x01 \x01(\tR\n" +
	"mountpoint\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x06 \x01(\x04R\tfreeBytes\x12!\n" +
	"\fused_percent\x18\a \x01(\x01R\vusedPercent\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\b \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\t \x01(\x04R\n" +
	"writeBytes\"\xb4\x02\n" +
	"\aNetwork\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x05 \x01(\x04R\vpacketsRecv\x12\x1f\n" +
	"\verrors_sent\x18\x06 \x01(\x04R\n" +
	"errorsSent\x12\x1f\n" +
	"\verrors_recv\x18\a \x01(\x04R\n" +
	"errorsRecv\x12\x1d\n" +
	"\n" +
	"drops_sent\x18\b \x01(\x04R\tdropsSent\x12\x1d\n" +
	"\n" +
	"drops_recv\x18\t \x01(\x04R\tdropsRecv2P\n" +
	"\x0eMetricsService\x12>\n" +
	"\rStreamMetrics\x12\x13.tz.v1.MetricReport\x1a\x16.google.protobuf.Empty(\x01B{\n" +
	"\tcom.tz.v1B\fMetricsProtoP\x01Z+github.com/djavgira/TZ/pkg/proto/tz/v1;tzv1\xa2\x02\x03TXX\xaa\x02\x05Tz.V1\xca\x02\x05Tz\\V1\xe2\x02\x11Tz\\V1\\GPBMetadata\xea\x02\x06Tz::V1b\x06proto3"

var (
	file_tz_v1_metrics_proto_rawDescOnce sync.Once
	file_tz_v1_metrics_proto_rawDescData []byte
)

func file_tz_v1_metrics_proto_rawDescGZIP() []byte {
	file_tz_v1_metrics_proto_rawDescOnce.Do(func() {
		file_tz_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tz_v1_metrics_proto_rawDesc), len(file_tz_v1_metrics_proto_rawDesc)))
	})
	return file_tz_v1_metrics_proto_rawDescData
}

var file_tz_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tz_v1_metrics_proto_goTypes = []any{
	(*MetricReport)(nil),          // 0: tz.v1.MetricReport
	(*CPU)(nil),                   // 1: tz.v1.CPU
	(*Memory)(nil),                // 2: tz.v1.Memory
	(*Disk)(nil),                  // 3: tz.v1.Disk
	(*Network)(nil),               // 4: tz.v1.Network
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_tz_v1_metrics_proto_depIdxs = []int32{
	5, // 0: tz.v1.MetricReport.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: tz.v1.MetricReport.cpu:type_name -> tz.v1.CPU
	2, // 2: tz.v1.MetricReport.memory:type_name -> tz.v1.Memory
	3, // 3: tz.v1.MetricReport.disks:type_name -> tz.v1.Disk
	4, // 4: tz.v1.MetricReport.networks:type_name -> tz.v1.Network
	0, // 5: tz.v1.MetricsService.StreamMetrics:input_type -> tz.v1.MetricReport
	6, // 6: tz.v1.MetricsService.StreamMetrics:output_type -> google.protobuf.Empty
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tz_v1_metrics_proto_init() }
func file_tz_v1_metrics_proto_init() {
	if File_tz_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tz_v1_metrics_proto_rawDesc), len(file_tz_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tz_v1_metrics_proto_goTypes,
		DependencyIndexes: file_tz_v1_metrics_proto_depIdxs,
		MessageInfos:      file_tz_v1_metrics_proto_msgTypes,
	}.Build()
	File_tz_v1_metrics_proto = out.File
	file_tz_v1_metrics_proto_goTypes = nil
	file_tz_v1_metrics_proto_depIdxs = nil
}
